name: Build Desktop App

on:
  push:
    branches: [ master, feature/nwjs ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Install wine
#        run: sudo apt-get install wine
#      - name: Install wine gecko
#        run: |
#          wget http://dl.winehq.org/wine/wine-gecko/2.47.2/wine-gecko-2.47.2-x86_64.msi
#          wine msiexec /i wine-gecko-2.47.2-x86_64.msi
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - id: set_var
        shell: bash
        run: |
          content=`cat ./package.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).name}}"
          echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
        shell: bash
      - name: Build App
        shell: bash
        run: |
          npm install
          npm run build:nw
      - uses: actions/upload-artifact@v2
        name: Store Linux x64
        with:
          name: kiri-moto-linux-x64
          path: dist/${{fromJson(steps.set_var.outputs.packageJson).name}}-${{fromJson(steps.set_var.outputs.packageJson).version}}-linux-x64.zip
      - uses: actions/upload-artifact@v2
        name: Store Linux x86
        with:
          name: kiri-moto-linux-x86
          path: dist/${{fromJson(steps.set_var.outputs.packageJson).name}}-${{fromJson(steps.set_var.outputs.packageJson).version}}-linux-x86.zip
      - uses: actions/upload-artifact@v2
        name: Store macOS x86
        with:
          name: kiri-moto-mac-x64
          path: dist/${{fromJson(steps.set_var.outputs.packageJson).name}}-${{fromJson(steps.set_var.outputs.packageJson).version}}-mac-x64.zip
      - uses: actions/upload-artifact@v2
        name: Store Windows x64
        with:
          name: kiri-moto-win-x64
          path: dist/${{fromJson(steps.set_var.outputs.packageJson).name}}-${{fromJson(steps.set_var.outputs.packageJson).version}}-win-x64.zip
